// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKL4iJUK9rnYBfDLsWI37ogSpqq0mPdo',
    appId: '1:925107840887:web:7c3969356fbb4d92f3e372',
    messagingSenderId: '925107840887',
    projectId: 'to-do-469ca',
    authDomain: 'to-do-469ca.firebaseapp.com',
    storageBucket: 'to-do-469ca.firebasestorage.app',
    measurementId: 'G-F4FN1PSGNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKRH_kd_jOaw1tb9JqvQQir0rfCYfVKco',
    appId: '1:925107840887:android:861cef2bdbfd5e7df3e372',
    messagingSenderId: '925107840887',
    projectId: 'to-do-469ca',
    storageBucket: 'to-do-469ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvN4WGtxRduNXusdHXNviLzA_8pjD-4DY',
    appId: '1:925107840887:ios:ddf99b31633dd32af3e372',
    messagingSenderId: '925107840887',
    projectId: 'to-do-469ca',
    storageBucket: 'to-do-469ca.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvN4WGtxRduNXusdHXNviLzA_8pjD-4DY',
    appId: '1:925107840887:ios:ddf99b31633dd32af3e372',
    messagingSenderId: '925107840887',
    projectId: 'to-do-469ca',
    storageBucket: 'to-do-469ca.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeKL4iJUK9rnYBfDLsWI37ogSpqq0mPdo',
    appId: '1:925107840887:web:1d9cbf7876881714f3e372',
    messagingSenderId: '925107840887',
    projectId: 'to-do-469ca',
    authDomain: 'to-do-469ca.firebaseapp.com',
    storageBucket: 'to-do-469ca.firebasestorage.app',
    measurementId: 'G-FVLJBT2CYG',
  );
}
